name: Create release
on:
  repository_dispatch:
    types: [ create-release ]

permissions:
  id-token: write
  contents: write
  packages: write

env:
  GO_VERSION: '1.23'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit
          disable-sudo: true
          disable-telemetry: true

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ env.GO_VERSION  }}

      - name: Checkout the repository at the given SHA from the artifact
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.client_payload.tag }}

      - name: Goreleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          version: latest
          args: release --clean --timeout 60m --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.event.client_payload.tag }}
